owner: rcm-agent
repo: rcm-dev-status

sites:
  - name: Frontend (dev)
    url: https://dev.basekey.ai/readyz
    method: GET
  - name: Orchestrator (dev)
    url: https://dev.basekey.ai/orchestrator/readyz
    method: GET
  - name: Web Agent (dev)
    url: https://dev.basekey.ai/rcm-web-agent/readyz
    method: GET
  - name: Memory (dev)
    url: https://dev.basekey.ai/api/memory/readyz
    method: GET

status-website:
  cname: status.dev.basekey.ai
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RCM Dev Status
  introTitle: "**RCM Dev Status** — readiness signals for dev.basekey.ai"
  introMessage: Public `/readyz` probes for the dev frontend, orchestrator, web-agent, and memory services (targets redacted). Incidents/uptime history update automatically from GitHub Actions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/rcm-agent/rcm-dev-status
